### ISSUE TITLE
メンバー情報の修正

### ISSUE THREAD

**Issue by aiotter** [aocsj/website#11]
- [ ] 岡元さん(yokamoto)の肩書きが事務局員になっているので、事務局長に修正する
- [ ] 理事会は理事と事務局長で構成されるため、[メンバー一覧](https://ocsj.asia/about/#members)をそれに合わせた表記にする
- [ ] 佐々木先生(hsasaki)の学歴を東京農業大学から東京農工大学に修正する

**Comment by aiotter** [comment]
@Yumi888 メンバーの顔写真なのですが、いまのところ佐々木先生の顔写真しか登録されていないので他の人の書いた記事がのっぺらぼうになってしまっています。
[この記事](https://ocsj.asia/2019/11/symposium-report/)でも、ページ最下部の執筆者情報のところで岡元さんの顔写真がないのでのっぺらぼうです。
顔写真があればここに表示することもできるのですが、どうしましょう？

**Comment by Yumi888** [comment]
> @Yumi888 メンバーの顔写真なのですが、いまのところ佐々木先生の顔写真しか登録されていないので他の人の書いた記事がのっぺらぼうになってしまっています。
> [この記事](https://ocsj.asia/2019/11/symposium-report/)でも、ページ最下部の執筆者情報のところで岡元さんの顔写真がないのでのっぺらぼうです。
> 顔写真があればここに表示することもできるのですが、どうしましょう？

返信、遅れました！顔写真、全員の入れましょうか！MLで意見聞いておきますね。

**Comment by Yumi888** [comment]
先程LINEのほうに学歴、自己紹介文章を送ったので、こちらの文章そのままコピペしていただけると幸いです！

**Comment by Yumi888** [comment]
ちなみに肩書について、事務局員のままなのですが、事務局長に変更可能でしょうか？

**Comment by Yumi888** [comment]
ただこの件は急ぎではないので、後回しでも全然大丈夫です！
