### ISSUE TITLE
メンバーの更新（安藤先生・岡田さん）

### ISSUE THREAD

**Issue by Yumi888** [aocsj/website#32]
・安藤先生を顧問から外す
・岡田さんを事務局員として追加

**Comment by aiotter** [comment]
和久さんの所属と私の所属も
https://github.com/aocsj/website/pull/45#pullrequestreview-448158991

**Comment by aiotter** [comment]
長田さんの記載事項の確認に時間がかかっているので、先に他のメンバーの修正を行います。長田さんについては #54 で扱います。
